type County = {
  id: number;
  name: string;
  country_code: string;
};

export const romaniaCounties: County[] = [
  { id: 1, name: "Alba", country_code: "RO" },
  { id: 2, name: "Arad", country_code: "RO" },
  { id: 3, name: "Argeș", country_code: "RO" },
  { id: 4, name: "Bacău", country_code: "RO" },
  { id: 5, name: "Bihor", country_code: "RO" },
  { id: 6, name: "Bistrița-Năsăud", country_code: "RO" },
  { id: 7, name: "Botoșani", country_code: "RO" },
  { id: 8, name: "Brașov", country_code: "RO" },
  { id: 9, name: "Brăila", country_code: "RO" },
  { id: 10, name: "Buzău", country_code: "RO" },
  { id: 11, name: "Caraș-Severin", country_code: "RO" },
  { id: 12, name: "Călărași", country_code: "RO" },
  { id: 13, name: "Cluj", country_code: "RO" },
  { id: 14, name: "Constanța", country_code: "RO" },
  { id: 15, name: "Covasna", country_code: "RO" },
  { id: 16, name: "Dâmbovița", country_code: "RO" },
  { id: 17, name: "Dolj", country_code: "RO" },
  { id: 18, name: "Galați", country_code: "RO" },
  { id: 19, name: "Giurgiu", country_code: "RO" },
  { id: 20, name: "Gorj", country_code: "RO" },
  { id: 21, name: "Harghita", country_code: "RO" },
  { id: 22, name: "Hunedoara", country_code: "RO" },
  { id: 23, name: "Ialomița", country_code: "RO" },
  { id: 24, name: "Iași", country_code: "RO" },
  { id: 25, name: "Ilfov", country_code: "RO" },
  { id: 26, name: "Maramureș", country_code: "RO" },
  { id: 27, name: "Mehedinți", country_code: "RO" },
  { id: 28, name: "Mureș", country_code: "RO" },
  { id: 29, name: "Neamț", country_code: "RO" },
  { id: 30, name: "Olt", country_code: "RO" },
  { id: 31, name: "Prahova", country_code: "RO" },
  { id: 32, name: "Satu Mare", country_code: "RO" },
  { id: 33, name: "Sălaj", country_code: "RO" },
  { id: 34, name: "Sibiu", country_code: "RO" },
  { id: 35, name: "Suceava", country_code: "RO" },
  { id: 36, name: "Teleorman", country_code: "RO" },
  { id: 37, name: "Timiș", country_code: "RO" },
  { id: 38, name: "Tulcea", country_code: "RO" },
  { id: 39, name: "Vaslui", country_code: "RO" },
  { id: 40, name: "Vâlcea", country_code: "RO" },
  { id: 41, name: "Vrancea", country_code: "RO" },
  { id: 42, name: "București", country_code: "RO" },
];
